// WARNING: This file is regenerated by the `cargo func new` command.
use azure_functions::codegen::Function;

mod greet;
#[cfg(feature = "unstable")]
mod greet_async;
mod greet_with_json;

// Export the Azure Functions here.
#[cfg(feature = "unstable")]
pub const EXPORTS: &[&Function] = &[
    &greet::GREET_FUNCTION,
    &greet_async::GREET_ASYNC_FUNCTION,
    &greet_with_json::GREET_WITH_JSON_FUNCTION,
];

// Export the Azure Functions here.
#[cfg(not(feature = "unstable"))]
pub const EXPORTS: &[&Function] = &[
    &greet::GREET_FUNCTION,
    &greet_with_json::GREET_WITH_JSON_FUNCTION,
];
