// WARNING: This file is regenerated by the `cargo func new` command.

mod greet;
mod greet_async;
mod greet_with_json;

// Export the Azure Functions here.
azure_functions::export! {
    greet::greet,
    greet_async::greet_async,
    greet_with_json::greet_with_json,
}
