# syntax=docker/dockerfile-upstream:experimental

FROM peterhuene/azure-functions-rs-build:{{crate_version}} AS builder

WORKDIR /src
COPY . /src

# Run with mounted cache
RUN --mount=type=cache,target=/src/target \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/usr/local/cargo/registry \
    ["cargo", "run", "--release", "--", "init", "--worker-path", "/usr/local/bin/rust_worker", "--script-root", "/home/site/wwwroot"]

# Sync extensions with mounted cache
# RUN --mount=type=cache,target=/src/target \
#     --mount=type=cache,target=/usr/local/cargo/git \
#     --mount=type=cache,target=/usr/local/cargo/registry \
#     ["cargo", "run", "--release", "--", "sync-extensions", "--script-root", "/home/site/wwwroot"]

FROM microsoft/azure-functions-dotnet-core2.0:2.0

# Copy from the build image
COPY --from=builder ["/usr/local/bin/rust_worker", "/usr/local/bin/rust_worker"]
COPY --from=builder ["/home/site/wwwroot", "/home/site/wwwroot"]
ADD ["https://raw.githubusercontent.com/peterhuene/azure-functions-rs/v{{crate_version}}/azure-functions/worker.config.json", "/azure-functions-host/workers/rust/worker.config.json"]
