// WARNING: This file is regenerated by the `cargo func new` command.

mod queue;
mod queue_with_output;

// Export the Azure Functions here.
azure_functions::export! {
    queue,
    queue_with_output,
}
