// WARNING: This file is regenerated by the `cargo func new` command.
use azure_functions::codegen::Function;

mod create_row;
mod read_row;

// Export the Azure Functions here.
pub const EXPORTS: &[&Function] = &[
    &create_row::CREATE_ROW_FUNCTION,
    &read_row::READ_ROW_FUNCTION,
];
