// WARNING: This file is regenerated by the `cargo func new` command.

mod blob_watcher;
mod copy_blob;
mod create_blob;
mod print_blob;

// Export the Azure Functions here.
azure_functions::export! {
    blob_watcher,
    copy_blob,
    create_blob,
    print_blob,
}
