// WARNING: This file is regenerated by the `cargo func new` command.
use azure_functions::codegen::Function;

mod blob_watcher;
mod copy_blob;
mod create_blob;
mod print_blob;

// Export the Azure Functions here.
pub const EXPORTS: &[&Function] = &[
    &blob_watcher::BLOB_WATCHER_FUNCTION,
    &copy_blob::COPY_BLOB_FUNCTION,
    &create_blob::CREATE_BLOB_FUNCTION,
    &print_blob::PRINT_BLOB_FUNCTION,
];
