// WARNING: This file is regenerated by the `cargo func new` command.
// Only the `azure_functions::export!` macro invocation will be preserved.

// Export the modules that define Azure Functions here.
azure_functions::export! {
    log_queue_message,
    create_queue_message,
    log_topic_message,
    create_topic_message,
}
