// WARNING: This file is regenerated by the `cargo func new` command.
use azure_functions::codegen::Function;

mod create_queue_message;
mod create_topic_message;
mod log_queue_message;
mod log_topic_message;

// Export the Azure Functions here.
pub const EXPORTS: &[&Function] = &[
    &create_queue_message::CREATE_QUEUE_MESSAGE_FUNCTION,
    &create_topic_message::CREATE_TOPIC_MESSAGE_FUNCTION,
    &log_queue_message::LOG_QUEUE_MESSAGE_FUNCTION,
    &log_topic_message::LOG_TOPIC_MESSAGE_FUNCTION,
];
