// WARNING: This file is regenerated by the `cargo func new` command.

#[cfg(feature = "unstable")]
mod call_hello_world;
#[cfg(feature = "unstable")]
mod hello_world;
#[cfg(feature = "unstable")]
mod say_hello;
#[cfg(feature = "unstable")]
mod start;

// Export the Azure Functions here.
#[cfg(feature = "unstable")]
azure_functions::export! {
    call_hello_world,
    hello_world,
    say_hello,
    start,
}

#[cfg(not(feature = "unstable"))]
azure_functions::export! {}
