// WARNING: This file is regenerated by the `cargo func new` command.

mod call_hello_world;
mod hello_world;
mod say_hello;
mod start;

// Export the Azure Functions here.
azure_functions::export! {
    call_hello_world::call_hello_world,
    hello_world::hello_world,
    say_hello::say_hello,
    start::start,
}
