// WARNING: This file is regenerated by the `cargo func new` command.
use azure_functions::codegen::Function;

mod send_email;

// Export the Azure Functions here.
pub const EXPORTS: &[&Function] = &[&send_email::SEND_EMAIL_FUNCTION];
