// WARNING: This file is regenerated by the `cargo func new` command.

mod add_to_group;
mod negotiate;
mod remove_from_group;
mod send_message;

// Export the Azure Functions here.
azure_functions::export! {
    add_to_group,
    negotiate,
    remove_from_group,
    send_message,
}
