// WARNING: This file is regenerated by the `cargo func new` command.
use azure_functions::codegen::Function;

mod add_to_group;
mod negotiate;
mod remove_from_group;
mod send_message;

// Export the Azure Functions here.
pub const EXPORTS: &[&Function] = &[
    &add_to_group::ADD_TO_GROUP_FUNCTION,
    &negotiate::NEGOTIATE_FUNCTION,
    &remove_from_group::REMOVE_FROM_GROUP_FUNCTION,
    &send_message::SEND_MESSAGE_FUNCTION,
];
