// WARNING: This file is regenerated by the `cargo func new` command.

mod create_event;
mod log_event;

// Export the Azure Functions here.
azure_functions::export! {
    create_event,
    log_event,
}
