// WARNING: This file is regenerated by the `cargo func new` command.
use azure_functions::codegen::Function;

mod create_event;
mod log_event;

// Export the Azure Functions here.
pub const EXPORTS: &[&Function] = &[
    &create_event::CREATE_EVENT_FUNCTION,
    &log_event::LOG_EVENT_FUNCTION,
];
