// WARNING: This file is regenerated by the `cargo func new` command.
use azure_functions::codegen::Function;

mod timer;

// Export the Azure Functions here.
pub const EXPORTS: &[&Function] = &[&timer::TIMER_FUNCTION];
