[package]
name = "event-grid-example"
version = "0.1.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
edition = "2018"

[dependencies]
azure-functions = { path = "../../azure-functions" }
log = "0.4.6"

[features]
unstable = ["azure-functions/unstable"]
