// WARNING: This file is regenerated by the `cargo func new` command.
use azure_functions::codegen::Function;

mod create_document;
mod log_documents;
mod query_documents;
mod read_document;

// Export the Azure Functions here.
pub const EXPORTS: &[&Function] = &[
    &create_document::CREATE_DOCUMENT_FUNCTION,
    &log_documents::LOG_DOCUMENTS_FUNCTION,
    &query_documents::QUERY_DOCUMENTS_FUNCTION,
    &read_document::READ_DOCUMENT_FUNCTION,
];
